<?php
function common_header() {
	global $name;
	?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
	<title>SCALE: Southern California Linux Expo 2003 - <? echo $name ?></title>
	<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
	<meta HTTP-EQUIV="Content-Language" CONTENT="en">
	<meta NAME="Keywords" CONTENT="scale, linux, expo, southern california, usc,
		usclug, ucla, uclalug, sclug, simi valley, conejo valley, los angeles">
	<meta NAME="Description" CONTENT="Southern California Linux Expo Webpage">
	<link REL="StyleSheet" TYPE="text/css" HREF="/past/2003/common/common.css">
	<link REL="shortcut icon" HREF="/favicon.ico">
</head>
<body>

<table BORDER="0" WIDTH="760" CELLSPACING="0" CELLPADDING="0">
<tr>
	<td WIDTH="760" VALIGN="TOP" COLSPAN="3" CLASS="bgwhite">
		<div ALIGN="CENTER">
		<img SRC="/past/2003/images/banner.jpg" WIDTH="760" HEIGHT="80" ALT="banner">
		</div>
	</td>
</tr>
<tr>

	<td COLSPAN="3">&nbsp;</td>
</tr>
<tr>
	<td WIDTH="150" VALIGN="TOP" CLASS="bgcolored" HEIGHT="400">
		<br>
		<b>Current Year:</b><br><br>
		<a HREF="/">Home</a><br><br>
		<b>2003 Archive:</b><br><br>
		<a HREF="/past/2003/index.php">Introduction</a><br><br>
		<a HREF="/past/2003/location.php">Location</a><br><br>
		<a HREF="/past/2003/speakers.php">Speakers</a><br><br>
		<a HREF="/past/2003/exhibitions.php">Exhibitions</a><br><br>
		<a HREF="/past/2003/hours.php">Schedule</a><br><br>
		<a HREF="/past/2003/sponsors.php">Sponsors</a><br><br>
		<a HREF="/past/2003/committees.php">Committees</a><br><br>
		<a HREF="/past/2003/pr.php">Media</a><br><br>
		<a HREF="/past/2003/pictures/">Event Pictures</a><br><br>
		<!-- <a HREF="/past/2003/cfp.php">Call For Papers</a><br><br> //-->
	</td>
	<td WIDTH="10" ROWSPAN="2">&nbsp;</td>
	<td WIDTH="600" VALIGN="TOP" ROWSPAN="2">

	<?
}

function common_footer() {
?>

</td>

</tr>
<tr>
<td valign="top">
<p CLASS="bannerl">
Hosted By:<br><br>
<a href="http://www.usc.edu"><img src="http://www.usc.edu/usc/img/01/mono-gold-cardinal-big.gif" alt="" width="94" height="75" border="0" /></a><br>
<a HREF="http://www.sclug.org/"><img SRC="/past/2003/images/logos/sclug.gif" BORDER="0" ALIGN="top"></a><br>
<a HREF="http://www.linux.ucla.edu/"><img SRC="/past/2003/images/logos/uclalug.gif" BORDER="0" ALIGN="top"></a>
</p>
</td>
</tr>
<tr>

	<td COLSPAN="3">&nbsp;</td>
</tr>
</table>

<table BORDER="0" WIDTH="760" CELLSPACING="0" CELLPADDING="0">
<tr>
	<td VALIGN="TOP" CLASS="bgblack">
		<div ALIGN="LEFT">
		| SCALE 2X:
		<FONT COLOR="#FF0000">S</FONT>outhern
		<FONT COLOR="#FF0000">Ca</FONT>lifornia
		<FONT COLOR="#FF0000">L</FONT>inux
		<FONT COLOR="#FF0000">E</FONT>xpo
		2003 |
		</div>
	</td>
	<td VALIGN="TOP" CLASS="bgblack">
		<div ALIGN="RIGHT">|
		<a HREF="/past/2003/contact.php" CLASS="black">Contact Us</a> |
		<a HREF="/past/2003/about.php" CLASS="black">About</a> |
		</div>
	</td>
</tr>
</table>

</body>
</html>

<?
}

?>


